package au.gov.dto.dibp.appointments.booking;

import au.gov.dto.dibp.appointments.client.Client;
import au.gov.dto.dibp.appointments.qflowintegration.ApiCallsSenderService;
import au.gov.dto.dibp.appointments.util.ResponseWrapper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.runners.MockitoJUnitRunner;

import java.time.LocalDateTime;
import java.util.Map;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

public class BookingServiceTest {

    @Test
    public void test_bookAnAppointment_should_returnAppointmentDateIfBookingSuccessful(){
        BookingService service = new BookingService(new ApiCallsSenderService() {
            @Override
            public ResponseWrapper sendRequest(String requestTemplatePath, Map<String, String> messageParams, String serviceAddress) {
                return getSuccessfulResponse();
            }
        }, "serviceUrl");

        LocalDateTime apptTime = LocalDateTime.of(2015, 12, 30, 13, 20, 0);
        String bookedDate = service.bookAnAppointment(getStandardClient(), apptTime);
        assertThat(bookedDate, is("2015-12-30T13:20:00"));
    }

    private Client getStandardClient (){
        return new Client("123", "Surname", "40404", false, true);
    }

    private ResponseWrapper getSuccessfulResponse(){
        String response =
                "<s:Body>\n" +
                "  <SetAppointmentResponse xmlns=\"http://www.qnomy.com/Services\">\n" +
                "         <SetAppointmentResult xmlns:b=\"http://schemas.datacontract.org/2004/07/QFlow.Library\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                "            <b:AppointmentId>113</b:AppointmentId>\n" +
                "            <b:CalendarId>1050</b:CalendarId>\n" +
                "            <b:CaseId>105</b:CaseId>\n" +
                "            <b:ProcessId>121</b:ProcessId>\n" +
                "            <b:SetAppointmentData>\n" +
                "               <b:AppointmentTypeId>2</b:AppointmentTypeId>\n" +
                "               <b:CustomerId>6</b:CustomerId>\n" +
                "               <b:DateAndTime>2015-12-30T13:20:00</b:DateAndTime>\n" +
                "               <b:Notes>This is generated by the API call</b:Notes>\n" +
                "               <b:UserId>3</b:UserId>\n" +
                "            </b:SetAppointmentData>\n" +
                "         </SetAppointmentResult>\n" +
                "      </SetAppointmentResponse>" +
                "</s:Body>";
        return new ResponseWrapper(200, response);
    }
}
